let shopItemsData = [
    {
        id: "arabica",
        name: "Arabica Coffee",
        price: 20,
        type: "green",
        img: "pictures/arabica.png",
    },
    {
        id: "robusta",
        name: "Robusta Coffee",
        price: 20,
        type: "green",
        img: "pictures/robusta.png",
    },
    {
        id: "moka",
        name: "Moka Coffee",
        price: 20,
        type: "italian",
        img: "pictures/moka.png",
    },
    {
        id: "latte",
        name: "Latte Coffee",
        price: 15,
        type: "italian",
        img: "pictures/latte.png",
    },
    {
        id: "catimor",
        name: "Catimor Coffee",
        price: 15,
        type: "roasted",
        img: "pictures/catimor.png",
    },
    {
        id: "cherry",
        name: "Cherry Coffee",
        price: 15,
        type: "green",
        img: "pictures/cherry.png",
    },
    {
        id: "culi",
        name: "Culi Coffee",
        price: 25,
        type: "roasted",
        img: "pictures/culi.png",
    },
    {
        id: "espresso",
        name: "Espresso Coffee",
        price: 25,
        type: "italian",
        img: "pictures/espresso.png",
    },
    {
        id: "typica",
        name: "Typica Coffee",
        price: 25,
        type: "roasted",
        img: "pictures/typica.png",
    },
];